/**
 * AI Engine — MediaPipe Hand Landmark Constants & Connections
 * Standard 21-point MediaPipe Hand Landmarker indexing and complete hand skeleton topology.
 */

export const HAND_LANDMARKS = {
  WRIST: 0,

  THUMB_CMC: 1,
  THUMB_MCP: 2,
  THUMB_IP: 3,
  THUMB_TIP: 4,

  INDEX_MCP: 5,
  INDEX_PIP: 6,
  INDEX_DIP: 7,
  INDEX_TIP: 8,

  MIDDLE_MCP: 9,
  MIDDLE_PIP: 10,
  MIDDLE_DIP: 11,
  MIDDLE_TIP: 12,

  RING_MCP: 13,
  RING_PIP: 14,
  RING_DIP: 15,
  RING_TIP: 16,

  PINKY_MCP: 17,
  PINKY_PIP: 18,
  PINKY_DIP: 19,
  PINKY_TIP: 20,
};

export const HAND_CONNECTIONS = [
  // Palm Base Connections from Wrist to Knuckles
  [HAND_LANDMARKS.WRIST, HAND_LANDMARKS.THUMB_CMC],
  [HAND_LANDMARKS.WRIST, HAND_LANDMARKS.INDEX_MCP],
  [HAND_LANDMARKS.WRIST, HAND_LANDMARKS.MIDDLE_MCP],
  [HAND_LANDMARKS.WRIST, HAND_LANDMARKS.RING_MCP],
  [HAND_LANDMARKS.WRIST, HAND_LANDMARKS.PINKY_MCP],

  // Palm Knuckle Connections
  [HAND_LANDMARKS.INDEX_MCP, HAND_LANDMARKS.MIDDLE_MCP],
  [HAND_LANDMARKS.MIDDLE_MCP, HAND_LANDMARKS.RING_MCP],
  [HAND_LANDMARKS.RING_MCP, HAND_LANDMARKS.PINKY_MCP],

  // Thumb Finger Chain
  [HAND_LANDMARKS.THUMB_CMC, HAND_LANDMARKS.THUMB_MCP],
  [HAND_LANDMARKS.THUMB_MCP, HAND_LANDMARKS.THUMB_IP],
  [HAND_LANDMARKS.THUMB_IP, HAND_LANDMARKS.THUMB_TIP],

  // Index Finger Chain
  [HAND_LANDMARKS.INDEX_MCP, HAND_LANDMARKS.INDEX_PIP],
  [HAND_LANDMARKS.INDEX_PIP, HAND_LANDMARKS.INDEX_DIP],
  [HAND_LANDMARKS.INDEX_DIP, HAND_LANDMARKS.INDEX_TIP],

  // Middle Finger Chain
  [HAND_LANDMARKS.MIDDLE_MCP, HAND_LANDMARKS.MIDDLE_PIP],
  [HAND_LANDMARKS.MIDDLE_PIP, HAND_LANDMARKS.MIDDLE_DIP],
  [HAND_LANDMARKS.MIDDLE_DIP, HAND_LANDMARKS.MIDDLE_TIP],

  // Ring Finger Chain
  [HAND_LANDMARKS.RING_MCP, HAND_LANDMARKS.RING_PIP],
  [HAND_LANDMARKS.RING_PIP, HAND_LANDMARKS.RING_DIP],
  [HAND_LANDMARKS.RING_DIP, HAND_LANDMARKS.RING_TIP],

  // Pinky Finger Chain
  [HAND_LANDMARKS.PINKY_MCP, HAND_LANDMARKS.PINKY_PIP],
  [HAND_LANDMARKS.PINKY_PIP, HAND_LANDMARKS.PINKY_DIP],
  [HAND_LANDMARKS.PINKY_DIP, HAND_LANDMARKS.PINKY_TIP],
];
